apiVersion: v1
kind: Service
metadata:
  name: python-helloworld
spec:
  selector:
    app: python-helloworld
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000 # Match the port in your deployment
  type: LoadBalancer # Change to NodePort if not using a cloud provider
